#!/bin/sh

export LANG="en_CA.ascii"
export NLSPATH=":%N.cat:/usr/share/locale/%L/messages/%N.cat:/usr/share/locale/%L/messages/%N:/usr/share/locale/%L/LC_MESSAGES/%N.cat:/usr/share/locale/%L/LC_MESSAGES/%N"
export PATH="/bin/:/usr/bin:/opt/bin/"
export ROOTPATH="/bin/:/usr/bin:/sbin/:/usr/sbin/:/opt/bin/:/opt/sbin/"
export SHELL="/bin/sh"
export TMPDIR="/tmp/"
export EDITOR="/bin/vi"
export PAGER="/bin/more"
